version: '3.8'  # It's good practice to use the latest version compatible with your features

services:
  web:
    build: .  # Build context for the web service
    command: ./start.sh  # Runs the start.sh script when the container starts
    volumes:
      - .:/app  # Mounts the current directory into the container
    ports:
      - "8000:8000"  # Map port 8000 on the host to port 8000 in the container
    env_file:
      - .env  # Load environment variables from the .env file
    environment:
      - DJANGO_SETTINGS_MODULE=follow_up_project.settings  # Set Django settings file
    depends_on:
      - postgres_db  # Ensures the database service starts before the web service

  postgres_db:
    image: postgres:13  # Postgres database service
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data in a named volume
    env_file:
      - .env  # Load environment variables from the .env file
    environment:
      POSTGRES_DB: ${DATABASE_NAME}        # The name of the database to create
      POSTGRES_USER: ${DATABASE_USER}      # The database user
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}  # The password for the user

volumes:
  postgres_data:  # Named volume for persistent Postgres data
