services:
  app:
    build: ./  # Ensure this directory contains a Dockerfile for building the app
    volumes:
      - ./tcgc_cms:/app  # Mount the local "django" directory to "/app" in the container
    ports:
      - "8000:8000"
    image: app:django
    container_name: django_container
    command: gunicorn follow_up_project.wsgi:application --bind "0.0.0.0:8000" --timeout=5 --threads=10

  nginx:
    build: ./nginx  # Ensure this directory contains a Dockerfile for building nginx
    ports:
      - "80:80"
    image: nginx:latest
    container_name: nginx_container
    links:
      - app  # Connects nginx to the app service
